/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TareaCompletada } from "./components/wc-eventos/TareaCompletada";
export { TareaCompletada } from "./components/wc-eventos/TareaCompletada";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface Page01 {
    }
    interface WcComponente01 {
    }
    interface WcComponente02 {
        "age": number;
        "name": string;
        "secondSurname": string;
    }
    interface WcComponente03 {
    }
    interface WcEventos {
    }
    interface WcPadre {
    }
}
export interface WcEventosCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcEventosElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPage01Element extends Components.Page01, HTMLStencilElement {
    }
    var HTMLPage01Element: {
        prototype: HTMLPage01Element;
        new (): HTMLPage01Element;
    };
    interface HTMLWcComponente01Element extends Components.WcComponente01, HTMLStencilElement {
    }
    var HTMLWcComponente01Element: {
        prototype: HTMLWcComponente01Element;
        new (): HTMLWcComponente01Element;
    };
    interface HTMLWcComponente02Element extends Components.WcComponente02, HTMLStencilElement {
    }
    var HTMLWcComponente02Element: {
        prototype: HTMLWcComponente02Element;
        new (): HTMLWcComponente02Element;
    };
    interface HTMLWcComponente03Element extends Components.WcComponente03, HTMLStencilElement {
    }
    var HTMLWcComponente03Element: {
        prototype: HTMLWcComponente03Element;
        new (): HTMLWcComponente03Element;
    };
    interface HTMLWcEventosElementEventMap {
        "tareaCompletadaEvento": TareaCompletada;
    }
    interface HTMLWcEventosElement extends Components.WcEventos, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWcEventosElementEventMap>(type: K, listener: (this: HTMLWcEventosElement, ev: WcEventosCustomEvent<HTMLWcEventosElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWcEventosElementEventMap>(type: K, listener: (this: HTMLWcEventosElement, ev: WcEventosCustomEvent<HTMLWcEventosElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWcEventosElement: {
        prototype: HTMLWcEventosElement;
        new (): HTMLWcEventosElement;
    };
    interface HTMLWcPadreElement extends Components.WcPadre, HTMLStencilElement {
    }
    var HTMLWcPadreElement: {
        prototype: HTMLWcPadreElement;
        new (): HTMLWcPadreElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "page-01": HTMLPage01Element;
        "wc-componente01": HTMLWcComponente01Element;
        "wc-componente02": HTMLWcComponente02Element;
        "wc-componente03": HTMLWcComponente03Element;
        "wc-eventos": HTMLWcEventosElement;
        "wc-padre": HTMLWcPadreElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface Page01 {
    }
    interface WcComponente01 {
    }
    interface WcComponente02 {
        "age"?: number;
        "name"?: string;
        "secondSurname"?: string;
    }
    interface WcComponente03 {
    }
    interface WcEventos {
        "onTareaCompletadaEvento"?: (event: WcEventosCustomEvent<TareaCompletada>) => void;
    }
    interface WcPadre {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "page-01": Page01;
        "wc-componente01": WcComponente01;
        "wc-componente02": WcComponente02;
        "wc-componente03": WcComponente03;
        "wc-eventos": WcEventos;
        "wc-padre": WcPadre;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "page-01": LocalJSX.Page01 & JSXBase.HTMLAttributes<HTMLPage01Element>;
            "wc-componente01": LocalJSX.WcComponente01 & JSXBase.HTMLAttributes<HTMLWcComponente01Element>;
            "wc-componente02": LocalJSX.WcComponente02 & JSXBase.HTMLAttributes<HTMLWcComponente02Element>;
            "wc-componente03": LocalJSX.WcComponente03 & JSXBase.HTMLAttributes<HTMLWcComponente03Element>;
            "wc-eventos": LocalJSX.WcEventos & JSXBase.HTMLAttributes<HTMLWcEventosElement>;
            "wc-padre": LocalJSX.WcPadre & JSXBase.HTMLAttributes<HTMLWcPadreElement>;
        }
    }
}
